spring:
  profiles:
    active: local

---
spring:
  profiles: local


  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: test
    driver-class-name: org.h2.Driver
mybatis:
  type-aliases-package: com.example.demo.mapper
  mapper-locations: mybatis/mapper/**/*.xml

server:
    port: 8082